### ISSUE TITLE
Generar reglas con conmutatividad

### ISSUE THREAD

**Issue by alexgadea** [alexgadea/fun#16]
Generar reglas con conmutatividad, como ya pasa para la asociatividad.
Por ejemplo, como axioma tenemos la regla "Neutro de la equivalencia a derecha" que aparece como

(p ≡ True) ≡ p

el cual lo podemos usar para probar por ejemplo que p ≡ (True ≡ p), es decir con la asociatividad "para el otro lado". Por lo tanto la siguiente prueba es valida.

let thm testAsoc = p ≡ (True ≡ p)
begin proof
p
≡ { Neutro de la equivalencia a derecha }
True ≡ p
end proof

**Comment by miguelpagano** [comment]
Creo que la prueba esa funciona porque leemos los axiomas con equivalentes como dos reglas de reescritura. Eso no es lo mismo que hacer reescritura móduloa asociatividad, que sería:
dado un axioma de la forma `(p ≡ q) ≡ w` poder reescribir `p ≡ (q ≡ r) ≡ s` a `w ≡ r ≡ s`.

**Comment by manugunther** [comment]
Este issue corresponde a Equ.
